version: '3'
services:
  frontend:
    image: node:18-alpine 
    container_name: react
    working_dir: /usr/src/app
    volumes:
      - ./frontend:/usr/src/app
    ports:
      - "5173:5173"  # Expose React development server
    command: ["sh", "-c", "npm start -- --host"]
    environment:
      - NODE_ENV=development
    depends_on:
      - backend


  backend:
    image: node:18-alpine 
    container_name: express
    working_dir: /usr/src/app
    volumes:
      - ./backend:/usr/src/app
    ports:
      - "4500:4500"  # API server
    command: ["sh", "-c", "npm install && node server.js"]
    environment:
      - NODE_ENV=development
      - PORT=4500
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=elearning
    depends_on:
      - db

  db:
    image: mysql:8.0 
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: elearning
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql 

  phpmyadmin:
    image: phpmyadmin 
    container_name: phpmyadmin 
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "200:80"
    depends_on:
      - db
    links:
      - db

volumes:
  mysql-data: 
