version: '3'
services:
  app:
    image: node:18-alpine
    container_name: your-app-name
    platform: linux/arm64
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    ports:
      - "99:4500"
    command: ["sh", "-c", "npm install && npm install vite --save-dev && node server.js"]
    environment:
      - NODE_ENV=production
      - PORT=4500
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=rootpassword
      - DB_NAME=your_db_name
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: your-db-name
    platform: linux/arm64
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: your_db_name
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$MYSQL_ROOT_PASSWORD"]
      interval: 30s
      retries: 5
      start_period: 30s
      timeout: 10s

  phpmyadmin:
    image: arm64v8/phpmyadmin
    container_name: phpmyadmin
    platform: linux/arm64
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: rootpassword
    ports:
      - "200:80"
    depends_on:
      - db
    links:
      - db

volumes:
  db-data:
